// src/settings.js
import {
  SK_KEY, SK_MODEL, SK_DIR, SK_TEMP, SK_CONTEXT, SK_VOICE_NAME, SK_SUP_EMAIL,
  SK_SEARCH_KEY, SK_EXT_CONTEXT, SK_PROVIDER, SK_CLAUDE_KEY, SK_GROQ_KEY,
  SK_OPENAI_KEY, SK_PERPLEXITY_KEY, SK_OLLAMA_URL, SK_MODEL_OLLAMA,
  SK_PRO, SK_FB_PASS
} from './constants.js';
import { getProviderForMode, _modelKey } from './providers/index.js';

// NOTE: These functions reference globals from app.js:
// MODEL_DEFAULT, addBubble, setDot, setTab, _updateDirectiveStrip,
// updateStorageMeter, _fbEnabled, _fbNodeHash, initFirebase, SK_FB_PASS (via app.js global)

export function isPro(){return!!localStorage.getItem(SK_PRO)}

export function getSettings(){const e=isPro();return{key:localStorage.getItem(SK_KEY)||"",model:localStorage.getItem(SK_MODEL)||MODEL_DEFAULT,directive:localStorage.getItem(SK_DIR)||"",temp:e&&parseFloat(localStorage.getItem(SK_TEMP))||.7,context:e?parseInt(localStorage.getItem(SK_CONTEXT))||14:6}}

export function saveSettings(){const e=document.getElementById("cfg-key").value.trim(),t=document.getElementById("cfg-directive").value.trim(),n=document.getElementById("cfg-voice").value,a=document.getElementById("cfg-sup-email").value.trim(),o=(document.getElementById("cfg-search-key")?.value||"").trim();e&&!e.startsWith("•")&&localStorage.setItem(SK_KEY,e),o&&!o.startsWith("•")&&localStorage.setItem(SK_SEARCH_KEY,o);const r=(document.getElementById("cfg-ext-context")?.value||"").trim();localStorage.setItem(SK_EXT_CONTEXT,r),["chat","viva","tools","report"].forEach(e=>{const t=document.getElementById(`cfg-prov-${e}`),n=document.getElementById(`cfg-model-${e}`);if(t&&t.value&&localStorage.setItem(`horatio_provider_${e}`,t.value),n&&n.value){const a=t?.value||getProviderForMode(e);localStorage.setItem(_modelKey(a,e),n.value)}});const s=document.getElementById("cfg-model-chat");s&&s.value&&localStorage.setItem(SK_MODEL,s.value);const i=document.getElementById("cfg-claude-key");if(i){const e=i.value.trim();e&&!e.startsWith("•")&&localStorage.setItem(SK_CLAUDE_KEY,e)}const l=document.getElementById("cfg-groq-key");if(l){const e=l.value.trim();e&&!e.startsWith("•")&&localStorage.setItem(SK_GROQ_KEY,e)}const _oai=document.getElementById("cfg-openai-key");if(_oai){const e=_oai.value.trim();e&&!e.startsWith("•")&&localStorage.setItem(SK_OPENAI_KEY,e)}const _pxi=document.getElementById("cfg-perplexity-key");if(_pxi){const e=_pxi.value.trim();e&&!e.startsWith("•")&&localStorage.setItem(SK_PERPLEXITY_KEY,e)}const c=document.getElementById("cfg-ollama-url");if(c){const e=c.value.trim();e&&localStorage.setItem(SK_OLLAMA_URL,e)}const d=document.getElementById("cfg-ollama-model");d&&d.value&&localStorage.setItem(SK_MODEL_OLLAMA,d.value),localStorage.setItem(SK_DIR,t),localStorage.setItem(SK_VOICE_NAME,n),a&&localStorage.setItem(SK_SUP_EMAIL,a);const u=(document.getElementById("cfg-zotero-key")?.value||"").trim(),m=(document.getElementById("cfg-zotero-uid")?.value||"").trim();if(u&&!u.startsWith("•")&&localStorage.setItem("horatio_zotero_key",u),m&&localStorage.setItem("horatio_zotero_uid",m),isPro()){localStorage.setItem(SK_TEMP,document.getElementById("cfg-temp").value),localStorage.setItem(SK_CONTEXT,document.getElementById("cfg-context").value);const e=document.getElementById("cfg-fb-pass").value.trim();if(e&&!e.startsWith("•"))localStorage.setItem(SK_FB_PASS,e),_fbEnabled||initFirebase(e);else if(!e){const e=localStorage.getItem(SK_FB_PASS);e&&!_fbEnabled&&initFirebase(e)}}setDot("active"),_updateDirectiveStrip(),setTab("chat"),addBubble("system","Horatio recalibrated. New directive active.")}

export function _refreshProviderUI(){const e=localStorage.getItem(SK_PROVIDER)||"gemini",t={gemini:"#1fb896",claude:"#f97316",groq:"#a78bfa",ollama:"#3b82f6",openai:"#10a37f",perplexity:"#6366f1"};["gemini","claude","groq","ollama","openai","perplexity"].forEach(n=>{const a=document.getElementById(`btn-provider-${n}`),o=document.getElementById(`prov-body-${n}`),r=n===e,s=t[n];a&&(a.classList.toggle("prov-open",r),a.style.color=r?s:"",a.style.borderColor=r?s+"66":"",a.style.background=r?s+"18":""),o&&o.classList.toggle("prov-open",r)}),Object.entries({claude:"cfg-claude-key-group",groq:"cfg-groq-key-group",ollama:"cfg-ollama-group",openai:"cfg-openai-key-group",perplexity:"cfg-perplexity-key-group"}).forEach(([t,n])=>{const a=document.getElementById(n);a&&(a.style.display=e===t?"":"none")});const n=document.querySelector(".s-group:has(#cfg-model-chat)")||document.getElementById("cfg-model-chat")?.closest(".s-group");n&&(n.style.display="ollama"===e?"none":"");const a=[{value:"gemini",label:"Gemini"},{value:"claude",label:"Claude"},{value:"groq",label:"Groq"},{value:"openai",label:"OpenAI"},{value:"perplexity",label:"Perplexity"},{value:"ollama",label:"Ollama"}].map(e=>`<option value="${e.value}">${e.label}</option>`).join("");["chat","viva","tools","report"].forEach(e=>{const t=document.getElementById(`cfg-prov-${e}`);t&&(t.innerHTML=a,t.value=getProviderForMode(e)),onModeProviderChange(e)});const o=document.getElementById("cfg-claude-key");o&&(o.value=localStorage.getItem(SK_CLAUDE_KEY)?"••••••••••••••••":"");const r=document.getElementById("cfg-groq-key");r&&(r.value=localStorage.getItem(SK_GROQ_KEY)?"••••••••••••••••":"");const _oak=document.getElementById("cfg-openai-key");_oak&&(_oak.value=localStorage.getItem(SK_OPENAI_KEY)?"••••••••••••••••":"");const _pak=document.getElementById("cfg-perplexity-key");_pak&&(_pak.value=localStorage.getItem(SK_PERPLEXITY_KEY)?"••••••••••••••••":"");const s=document.getElementById("cfg-ollama-url");s&&!s.value&&(s.value=localStorage.getItem(SK_OLLAMA_URL)||"http://localhost:11434");const i=document.getElementById("cfg-ollama-model");if(i&&!i.options.length){const e=localStorage.getItem(SK_MODEL_OLLAMA)||"";i.innerHTML=e?`<option value="${e}">${e}</option>`:'<option value="">Click "Detect Models" to load</option>'}}

export function onModeProviderChange(e){const t=document.getElementById(`cfg-prov-${e}`),n=document.getElementById(`cfg-model-${e}`);if(!t||!n)return;const a=t.value,o={gemini:[{value:"gemini-2.5-flash",label:"gemini-2.5-flash — Fast"},{value:"gemini-2.5-pro",label:"gemini-2.5-pro — Deep"},{value:"gemini-2.0-flash",label:"gemini-2.0-flash — Light"}],claude:[{value:"claude-opus-4-7",label:"Opus 4.7 — Most capable"},{value:"claude-sonnet-4-6",label:"Sonnet 4.6 — Balanced"},{value:"claude-haiku-4-5-20251001",label:"Haiku 4.5 — Fast"}],groq:[{value:"llama-3.3-70b-versatile",label:"Llama 3.3 70B — Best"},{value:"llama-3.1-8b-instant",label:"Llama 3.1 8B — Fast"},{value:"gemma2-9b-it",label:"Gemma 2 9B"}],ollama:[{value:localStorage.getItem(SK_MODEL_OLLAMA)||"phi4-mini",label:localStorage.getItem(SK_MODEL_OLLAMA)||"phi4-mini (local)"}],openai:[{value:"gpt-4o",label:"GPT-4o — Best"},{value:"gpt-4o-mini",label:"GPT-4o mini — Fast"},{value:"gpt-4.1",label:"GPT-4.1"},{value:"o4-mini",label:"o4-mini — Reasoning"}],perplexity:[{value:"sonar-pro",label:"Sonar Pro — Best"},{value:"sonar",label:"Sonar — Fast"},{value:"sonar-reasoning-pro",label:"Sonar Reasoning Pro"}]},r=o[a]||o.gemini,s=localStorage.getItem(_modelKey(a,e));n.innerHTML=r.map(e=>`<option value="${e.value}"${e.value===s?" selected":""}>${e.label}</option>`).join(""),s||(n.value=r[0].value)}

export async function loadSettingsUI(){const e=getSettings(),t=isPro();document.getElementById("cfg-key").value=e.key?"••••••••••••••••":"",document.getElementById("cfg-directive").value=e.directive,document.getElementById("cfg-voice").value=localStorage.getItem(SK_VOICE_NAME)||"Charon",document.getElementById("cfg-sup-email").value=localStorage.getItem(SK_SUP_EMAIL)||"";const n=document.getElementById("cfg-zotero-key");n&&(n.value=localStorage.getItem("horatio_zotero_key")?"••••••••••••••••":"");const a=document.getElementById("cfg-zotero-uid");a&&(a.value=localStorage.getItem("horatio_zotero_uid")||"");const o=document.getElementById("cfg-search-key");o&&(o.value=localStorage.getItem(SK_SEARCH_KEY)?"••••••••••••••••":"");const r=document.getElementById("cfg-ext-context");r&&(r.value=localStorage.getItem(SK_EXT_CONTEXT)||"");const s=document.getElementById("cfg-context"),i=document.getElementById("cfg-temp");s.value=e.context,i.value=e.temp,s.disabled=!t,i.disabled=!t,document.getElementById("cfg-context-val").textContent=e.context,document.getElementById("cfg-temp-val").textContent=parseFloat(e.temp).toFixed(1);const l=localStorage.getItem(SK_PRO);document.getElementById("cfg-pro").value=l?"••••••••••••••••":"";const c=document.getElementById("pro-status-display");if(l?(c.style.color="var(--pulse)",c.textContent="✓ PRO ACTIVE — all features unlocked"):c.textContent="",document.getElementById("pro-behaviour-note").style.display=t?"none":"inline",["fb-pass-group","fb-help-note"].forEach(e=>{const n=document.getElementById(e);n&&(n.style.opacity=t?"1":"0.3")}),document.getElementById("sync-pro-note").style.display=t?"none":"inline",document.getElementById("cfg-fb-pass").disabled=!t,t){document.getElementById("cfg-fb-pass").value=localStorage.getItem(SK_FB_PASS)?"••••••••••••••••":"";const e=document.getElementById("fb-status-display");e&&_fbEnabled&&(e.style.color="var(--pulse)",e.textContent=`✓ SYNC ACTIVE — node ${_fbNodeHash?.slice(0,16)}...`)}updateStorageMeter(),_refreshProviderUI()}
